Repository osTicket/osTicket, pull requests merged in 2019-09, with the labels that each got.

#2924 Fix New Ticket Cancel Button
  include/client/open.inc.php
  include/staff/ticket-open.inc.php
Labels: review

#3476 Client FAQ Last Updated Time
  include/client/faq.inc.php
Labels: bug

#3522 Client Side Long FAQ Title
  assets/default/css/theme.css
Labels: bug

#3543 Custom Form Deletion
  include/staff/templates/form-manage.tmpl.php
Labels: Forms - Customer, bug

#4984 Introducing Schedules / Business Hours for SLAs (upgrade required)
  bootstrap.php
  include/ajax.schedule.php
  include/class.businesshours.php
  include/class.config.php
  include/class.dept.php
  include/class.format.php
  include/class.forms.php
  include/class.i18n.php
  include/class.nav.php
  include/class.schedule.php
  include/class.sla.php
  include/class.ticket.php
  include/i18n/en_US/help/tips/manage.schedule.yaml
  include/i18n/en_US/help/tips/manage.sla.yaml
  include/i18n/en_US/help/tips/settings.system.yaml
  include/i18n/en_US/help/tips/staff.department.yaml
  include/i18n/en_US/schedule.yaml
  include/staff/department.inc.php
  include/staff/schedule.inc.php
  include/staff/schedules.inc.php
  include/staff/settings-system.inc.php
  include/staff/slaplan.inc.php
  include/staff/templates/schedule-add.tmpl.php
  include/staff/templates/schedule-diagnostic.tmpl.php
  include/staff/templates/schedule-entries.tmpl.php
  include/staff/templates/schedule-entry.tmpl.php
  include/staff/templates/schedule-holidays.tmpl.php
  include/upgrader/streams/core.sig
  include/upgrader/streams/core/00c949a6-8b923d61.patch.sql
  include/upgrader/streams/core/00c949a6-8b923d61.task.php
  scp/ajax.php
  scp/schedules.php
  setup/inc/streams/core/install-mysql.sql
Labels: Database, SLA

#5008 Add thread_type Field
  include/class.report.php
  include/class.task.php
  include/class.thread.php
  include/class.ticket.php
  include/upgrader/streams/core.sig
  include/upgrader/streams/core/9b5550da-e6978154.patch.sql
  setup/inc/streams/core/install-mysql.sql
Labels: Database

#5025 issue: Form Field Flags
  include/i18n/en_US/form.yaml
  include/staff/dynamic-form.inc.php
  include/upgrader/streams/core/9b5550da-e6978154.cleanup.sql
  include/upgrader/streams/core/9b5550da-e6978154.patch.sql
Labels: Database

#5063 issue: Staff/User Email Length
  include/upgrader/streams/core.sig
  include/upgrader/streams/core/e6978154-cc6d1b03.patch.sql
  setup/inc/streams/core/install-mysql.sql
Labels: Database
